env:
  PRODUCT_VERSION: "1.6.3"
  NOMAD_ADDR: "http://4b7d-50-46-255-119.ngrok-free.app"

jobs:
  Check-Nomad-Status:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup `nomad`
        uses: lucasmelin/setup-nomad@v1
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}
      - name: Run `nomad version`
        run: "nomad version"
      - name: Auth Into Nomad
        id: nomad-jwt-auth
        uses: mikenomitch/nomad-jwt-auth@v1
        with:
          url: ${{ env.NOMAD_ADDR }}
          caCertificate: ${{ secrets.NOMAD_CA_CERT }}
        continue-on-error: true
      - name: Deploy Jobs
        run: NOMAD_ADDR="${{ env.NOMAD_ADDR }}" NOMAD_TOKEN="${{ steps.nomad-jwt-auth.outputs.nomadToken }}" for file in ./nomad-jobs/*; do nomad run -detach "$file"; done
